name: lucio
description: A new Flutter project.
publish_to: 'none'

version: 1.0.17

environment:
  sdk: '>=3.1.0-129.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #STATES
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  #ROUTER
  go_router: ^6.5.8
  #SCREEN
  responsive_framework: ^1.0.0
  #DEVICE
  local_auth: ^2.1.6
  device_info_plus: ^8.2.0
  package_info_plus: ^3.1.0
  no_screenshot: ^0.0.1+6
  flutter_keyboard_visibility: ^5.4.1
  #DESIGN
  flash: ^3.0.3
  timeago: ^3.4.0
  fl_chart: ^0.63.0
  animations: ^2.0.7
  animate_do: ^3.0.2
  sliver_tools: ^0.2.10
  flutter_slidable: ^3.0.0
  flex_color_picker: ^3.2.2
  flutter_screen_lock: ^7.0.4
  customizable_counter: ^1.0.4
  modal_bottom_sheet: ^3.0.0-pre
  flutter_staggered_grid_view: ^0.6.2
  #UTILS
  intl: ^0.18.1
  collection: ^1.17.2
  file_picker: ^5.3.0
  path_provider: ^2.0.14
  dropdown_search: ^5.0.6
  easy_localization: ^3.0.1
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^8.0.0
  #DATABASE
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.0
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.2.0

  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.2
  #GOOGLE DRIVE
  driven: ^0.1.4
  google_sign_in: ^5.4.0
  googleapis: ^9.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  #GENERATOR
  build_runner: ^2.3.3
  freezed: ^2.3.2
  isar_generator: ^3.1.0+1
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - .env
